name: Flask Docker CI/CD

on:
  pull_request:
    branches:
      - master             # PR targets the master branch
    paths-ignore:
      - "**/README.md"    # Optional: Ignore changes to specific files (e.g., README)

jobs:
  build-docker:
    name: Build Docker Image
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout code
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Check the source branch name
      - name: Validate source branch
        run: |
          if [[ ! "${{ github.head_ref }}" =~ ^(feature/|fix/) ]]; then
            echo "PR source branch does not match 'feature/' or 'fix/' pattern. Exiting."
            exit 1
          fi
        shell: bash

      # Step 2: Build Docker image
      - name: Build Docker image
        run: |
          docker build -t anushavangavolu/flask-api:pr-${{ github.event.pull_request.number }} .

  push-docker:
    name: Push Docker Image to DockerHub
    runs-on: ubuntu-latest
    needs: build-docker  # Only run if the build-docker job succeeds
    if: github.ref == 'refs/heads/main'  # Only push when on the main branch

    steps:
      # Step 1: Checkout code
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Log in to DockerHub
      - name: Log in to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Step 3: Push Docker image
      - name: Push Docker image
        run: |
          docker tag anushavangavolu/flask-api:pr-${{ github.event.pull_request.number }} anushavangavolu/flask-api:pr-${{ github.head_ref }}
          docker push anushavangavolu/flask-api:pr-${{ github.head_ref }}
