name: Flask Docker CI/CD

on:
  push:
    branches:
      - main                  # Trigger on pushes to main (for pushing to DockerHub)
      - feature/**            # Trigger on branches starting with "feature/"
      - fix/**                # Trigger on branches starting with "fix/"
  pull_request:
    branches:
      - main                  # Trigger when pull requests are made to main

jobs:
  build-docker:
    name: Build Docker Image
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout code
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Get the short commit hash
      - name: Get commit hash
        id: commit
        run: echo "commit_hash=$(git rev-parse --short HEAD)" >> $GITHUB_ENV

      # Step 2: Build Docker image
      - name: Build Docker image
        run: |
          docker build -t anushavangavolu/flask-api:${{ env.commit_hash }} .
          docker tag anushavangavolu/flask-api:${{ env.commit_hash }} anushavangavolu/flask-api:latest

  push-docker:
    name: Push Docker Image to DockerHub
    runs-on: ubuntu-latest
    needs: build-docker  # Only run if the build-docker job succeeds
    if: github.ref == 'refs/heads/main'  # Only push when on the main branch

    steps:
      # Step 2: Log in to DockerHub
      - name: Log in to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Get commit hash
        id: commit
        run: echo "commit_hash=$(git rev-parse --short HEAD)" >> $GITHUB_ENV
        
      # Step 3: Push Docker image
      - name: Push Docker image
        run: |
          docker push anushavangavolu/flask-api:${{ env.commit_hash }}
          docker push anushavangavolu/flask-api:latest
